POST http://localhost:4040/api/auth/login
Content-Type: application/json

{
    "email":"test",
    "mdp": "ttttt"
}
### 
GET http://localhost:4040/api/forum/posts

###
GET http://localhost:4040/api/forum/post/14

headers:{
    "Authorization": "Bearer KSA29E432SVOkeAbarh3gIUzHp9OsjWmQdOdnAnC7Os"
}
###
POST http://localhost:4040/api/forum/reponse
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJpYXQiOjE1OTEwOTk2NTYsImV4cCI6MTU5MTE4NjA1Nn0.F4C6ICOj5lVkSB2uOEiEqQFRfgxBn0m-YMjufurWLZM

{
    "id_question" : 14,
    "auteur" : "Oim-D",
   "message": "From req rest",
    "salon": "forum"
}

###

DELETE http://localhost:4040/api/forum/deleteone/33
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMSIsImlhdCI6MTU5MTM1MzE3OCwiZXhwIjoxNTkxNDM5NTc4fQ.tYYO0OTDt8Ttp_qSY6iSJvaYUkU3QNRuW5uar4o9LZE

###

GET http://localhost:4040/api/test/get

###

PUT http://localhost:4040/api/forum/modifier/34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJpYXQiOjE1OTE0Mjc3NzUsImV4cCI6MTU5MTUxNDE3NX0.xylTUlpi5CugHwE5L0o8gIYnCs9Octyzl5ZHcqFxqIc

{
    "message":"test",
    "urlimg":"http://"
}

###