POST http://localhost:4040/api/auth/login
Content-Type: application/json

{
    "email":"test",
    "mdp": "ttttt"
}
### 
GET http://localhost:4040/api/forum/posts

###
POST http://localhost:4040/api/forum/reponse
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJpYXQiOjE1OTEwOTk2NTYsImV4cCI6MTU5MTE4NjA1Nn0.F4C6ICOj5lVkSB2uOEiEqQFRfgxBn0m-YMjufurWLZM

{
    "id_question" : 14,
    "auteur" : "Oim-D",
   "message": "From req rest",
    "salon": "forum"
}

###

DELETE http://localhost:4040/api/forum/deleteone/33
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMSIsImlhdCI6MTU5MTM1MzE3OCwiZXhwIjoxNTkxNDM5NTc4fQ.tYYO0OTDt8Ttp_qSY6iSJvaYUkU3QNRuW5uar4o9LZE

###

GET http://localhost:4040/api/test/get

###

PUT http://localhost:4040/api/forum/modifier/34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJpYXQiOjE1OTE0Mjc3NzUsImV4cCI6MTU5MTUxNDE3NX0.xylTUlpi5CugHwE5L0o8gIYnCs9Octyzl5ZHcqFxqIc

{
    "message":"test",
    "urlimg":"http://"
}

###
DELETE http://localhost:4040/api/market/deleteone/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMSIsImlhdCI6MTU5MTY3ODUzNiwiZXhwIjoxNTkxNzY0OTM2fQ.f9NJ_SJc0a2NtK6f1Jwi7VCkJFhyO_jPwC20yxr1ujs
###
POST http://localhost:4040/api/rezo/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMSIsImlhdCI6MTU5MTY3ODUzNiwiZXhwIjoxNTkxNzY0OTM2fQ.f9NJ_SJc0a2NtK6f1Jwi7VCkJFhyO_jPwC20yxr1ujs

{
    "auteur":"another",
    "message":"va savoir Charles"
}

###
GET http://localhost:4040/api/market/see/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMSIsImlhdCI6MTU5MTc2NDY5MywiZXhwIjoxNTkxODUxMDkzfQ.nIb436DB4wNmXEAGB5lwxbJGv8XfhXl3xA6VcB77riQ

###
POST http://localhost:4040/api/market/classeur
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJpYXQiOjE1OTE5NTcyNzcsImV4cCI6MTU5MjA0MzY3N30.sYY9cB0TJxV-nCD_RKxaJ5RhBKuHnbdhd0x9uNy4k2Q

{
    "catégorie":"auto"
}

###